@startuml
left to right direction

actor Пользователь
actor Администратор
actor Гость
actor "Система журналирования" as Journal


Администратор -|>  Пользователь
Пользователь -|> Гость

Пользователь -- (Управлять файлами)

(Управлять файлами) --> (Загрузить файл)
(Управлять файлами) --> (Удалить файл)

(Загрузить файл) .> (Проверить квоту) : <<include>>
(Загрузить файл) <. (Поделиться файлом) : <<extend>>
(Удалить файл) .> (Подтвердить удаление) : <<include>>

(Поделиться файлом) <. (Создать ссылку для публикации) : <<extend>>

(Скачать файл) .> (Проверить антивирусом) : <<include>>
(Скачать файл) .> (Просмотреть список файлов) : <<extend>>

Гость -- (Просмотреть список файлов)

Гость -- (Поиск файлов)

Администратор -- (Создать резервную копию)
Администратор -- (Восстановить из резервной копии)

Journal -- (Загрузить файл)

@enduml
