//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CloudFile.cpp
//  @ Date : 19.12.2025
//  @ Author : 
//
//


#include "CloudFile.h"

String CloudFile::getFileInfo() {

}

List<Byte> CloudFile::read() {

}

