//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CloudStorage.cpp
//  @ Date : 19.12.2025
//  @ Author : 
//
//


#include "CloudStorage.h"
#include "CloudFile.h"
#include "User.h"

void CloudStorage::addFile(CloudFile file) {

}

CloudFile CloudStorage::fetchFile(String fileName, User requester) {

}

