# -*- coding: utf-8 -*-
"""lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfkCQA_nGO3ruYTf4dS9ue9y4PM44_lP
"""

!pip install gradio kaggle -q



"""# Новый раздел"""

from google.colab import userdata
import os

os.environ['KAGGLE_TOKEN'] = userdata.get('KAGGLE_TOKEN')

# Скачиваем датасет
!kaggle datasets download -d asdasdasasdas/garbage-classification
!unzip -q garbage-classification.zip -d data

data_dir = '/content/data/Garbage classification/Garbage classification'
classes = os.listdir(data_dir)
print("Классы:", classes)

for cls in classes:
    count = len(os.listdir(os.path.join(data_dir, cls)))
    print(f"  {cls}: {count} фото")

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

data_dir = '/content/data/Garbage classification/Garbage classification'

# Аугментация — искусственно увеличиваем разнообразие данных
# поворачиваем, отражаем, зумируем фото чтобы модель лучше обобщала
datagen = ImageDataGenerator(
    rescale=1./255,        # нормализация пикселей 0-255 → 0-1
    validation_split=0.2,  # 20% данных — на проверку
    rotation_range=20,
    horizontal_flip=True,
    zoom_range=0.2
)

train_data = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=32,
    subset='training'
)

val_data = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=32,
    subset='validation'
)

print("Классы:", train_data.class_indices)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

# Загружаем MobileNetV2 без последнего слоя
base_model = MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,  # убираем оригинальный классификатор
    weights='imagenet'  # веса с обучения на миллионах картинок
)
base_model.trainable = False  # замораживаем — не трогаем чужие веса

# Добавляем свой классификатор под 6 классов
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(6, activation='softmax')  # 6 классов мусора
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_data,
    epochs=10,
    validation_data=val_data,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            patience=3,              # остановить если 3 эпохи нет улучшений
            restore_best_weights=True
        )
    ]
)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Обучение')
plt.plot(history.history['val_accuracy'], label='Валидация')
plt.title('Точность')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Обучение')
plt.plot(history.history['val_loss'], label='Валидация')
plt.title('Ошибка')
plt.legend()

plt.show()

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Предсказания на валидационной выборке
val_data.reset()
y_pred = model.predict(val_data, verbose=0)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = val_data.classes

# Имена классов
class_labels = list(val_data.class_indices.keys())

# Полный отчёт: precision, recall, f1-score по каждому классу
print(classification_report(y_true, y_pred_classes, target_names=class_labels, digits=3))

# Матрица ошибок
cm = confusion_matrix(y_true, y_pred_classes)
print(cm)

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

# --- если ты ещё не получил предсказания, раскомментируй: ---
# y_pred = model.predict(eval_data, verbose=0)
# y_pred_classes = np.argmax(y_pred, axis=1)
# y_true = eval_data.classes
# class_labels = list(eval_data.class_indices.keys())

# Русские названия для подписей
class_labels_ru = ['картон', 'стекло', 'металл', 'бумага', 'пластик', 'прочий']


# === График 1. Кривые обучения ===
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(history.history['accuracy'], label='Обучение', linewidth=2)
axes[0].plot(history.history['val_accuracy'], label='Валидация', linewidth=2)
axes[0].set_title('Точность по эпохам')
axes[0].set_xlabel('Эпоха')
axes[0].set_ylabel('Accuracy')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history.history['loss'], label='Обучение', linewidth=2)
axes[1].plot(history.history['val_loss'], label='Валидация', linewidth=2)
axes[1].set_title('Функция потерь по эпохам')
axes[1].set_xlabel('Эпоха')
axes[1].set_ylabel('Loss')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('learning_curves.png', dpi=150, bbox_inches='tight')
plt.show()


# === График 2. Матрица ошибок ===
cm = confusion_matrix(y_true, y_pred_classes)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=class_labels_ru,
    yticklabels=class_labels_ru,
    cbar_kws={'label': 'Количество'}
)
plt.xlabel('Предсказанный класс')
plt.ylabel('Истинный класс')
plt.title('Матрица ошибок')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()


# === График 3. Метрики по классам ===
precision, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred_classes)

x = np.arange(len(class_labels_ru))
width = 0.25

fig, ax = plt.subplots(figsize=(10, 5))
ax.bar(x - width, precision, width, label='Precision', color='#1f77b4')
ax.bar(x,         recall,    width, label='Recall',    color='#ff7f0e')
ax.bar(x + width, f1,        width, label='F1-score',  color='#2ca02c')

ax.set_xticks(x)
ax.set_xticklabels(class_labels_ru)
ax.set_ylabel('Значение метрики')
ax.set_ylim(0, 1.05)
ax.set_title('Метрики качества по классам')
ax.legend()
ax.grid(True, alpha=0.3, axis='y')

# Подписи значений над столбцами
for i, (p, r, fs) in enumerate(zip(precision, recall, f1)):
    ax.text(i - width, p + 0.02, f'{p:.2f}', ha='center', fontsize=8)
    ax.text(i,         r + 0.02, f'{r:.2f}', ha='center', fontsize=8)
    ax.text(i + width, fs + 0.02, f'{fs:.2f}', ha='center', fontsize=8)

plt.tight_layout()
plt.savefig('metrics_per_class.png', dpi=150, bbox_inches='tight')
plt.show()


print("Сохранены: learning_curves.png, confusion_matrix.png, metrics_per_class.png")

import gradio as gr
import numpy as np
import cv2
import tensorflow as tf
import os
import random

class_names = {v: k for k, v in train_data.class_indices.items()}

# === Grad-CAM ===
def make_gradcam_heatmap(img_array, model, last_conv_layer_name="Conv_1"):
    base_model = model.layers[0]  # MobileNetV2 (Functional, у него output есть)
    last_conv_layer = base_model.get_layer(last_conv_layer_name)

    # Модель: вход → (карта признаков, выход base_model)
    feature_model = tf.keras.Model(
        inputs=base_model.input,
        outputs=[last_conv_layer.output, base_model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, base_output = feature_model(img_array)

        # Прогоняем через остальные слои (pooling, dense, dropout, softmax)
        x = base_output
        for layer in model.layers[1:]:
            x = layer(x)
        predictions = x

        pred_index = tf.argmax(predictions[0])
        class_channel = predictions[:, pred_index]

    # Градиенты предсказанного класса по карте признаков
    grads = tape.gradient(class_channel, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    # Взвешиваем карты по важности
    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    # Нормализуем в [0, 1]
    heatmap = tf.maximum(heatmap, 0) / (tf.math.reduce_max(heatmap) + 1e-10)
    return heatmap.numpy()


def overlay_heatmap(img, heatmap, alpha=0.4):
    """Накладываем тепловую карту на оригинал."""
    heatmap = cv2.resize(heatmap, (img.shape[1], img.shape[0]))
    heatmap = np.uint8(255 * heatmap)
    heatmap_colored = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)
    overlay = cv2.addWeighted(img.astype(np.uint8), 1 - alpha, heatmap_colored, alpha, 0)
    return overlay


# === Функция предсказания ===
def predict(img):
    if img is None:
        return None, None

    img_resized = tf.image.resize(img, (224, 224)).numpy()
    img_for_model = np.expand_dims(img_resized / 255.0, 0).astype(np.float32)

    # Предсказание
    predictions = model.predict(img_for_model, verbose=0)[0]
    probs = {class_names[i]: float(predictions[i]) for i in range(len(class_names))}

    # Тепловая карта
    heatmap = make_gradcam_heatmap(img_for_model, model)
    overlay = overlay_heatmap(img_resized.astype(np.uint8), heatmap)

    return probs, overlay


# === Готовим примеры (по одному фото из каждого класса) ===
example_paths = []
for cls in os.listdir(data_dir):
    cls_dir = os.path.join(data_dir, cls)
    files = os.listdir(cls_dir)
    example_paths.append(os.path.join(cls_dir, random.choice(files)))


# === Интерфейс ===
app = gr.Interface(
    fn=predict,
    inputs=gr.Image(label="Загрузите фото мусора"),
    outputs=[
        gr.Label(num_top_classes=6, label="Предсказание"),
        gr.Image(label="Карта внимания (Grad-CAM)")
    ],
    title="🗑️ Классификатор мусора",
    description=(
        "Загрузи фото мусора — модель определит его тип. "
        "Справа покажется тепловая карта: красные участки — то, "
        "на что модель смотрела при принятии решения."
    ),
    examples=example_paths
)

app.launch(share=True, debug=True)