@startuml
actor "Пользователь" as User
participant "FileController" as FC
participant "StorageService" as Storage
participant "VirusScanner" as AV
participant "Journal" as Journal

== Инициирование загрузки ==
User -> FC ++: Инициировать загрузку
FC -> Journal : Записать событие: загрузка
FC -> Storage ++: Запрос квоты
Storage --> FC --: Получить квоту
break
else Квоты недостаточно
    FC -> User : Ошибка: квота превышена
    FC -> Journal : Записать событие: недостаточно_квоты
end

== Передача частей файла (loop) ==
loop for each chunk in file.chunks
    User -> FC : Отправить часть
    FC -> Storage ++: Сохранить часть
    Storage --> FC --: Результат сохранения
    break Ошибка при сохранении
    else
    FC -> User: Ошибка: ошибка при загрузке файла
    FC -> Journal: Записать событие: ошибка_загрузки
    end
end

== Сбор частей в файл и параллельные задачи ==
Storage -> Storage++-- : Сбор частей в файл
Storage --> FC : Загруженный файл

par Обработка файла и антивирус параллельно
    ' === Ветка 1: Пайплайн обработки файлов ===
    FC -> Converter++ : Обработка файла
    Converter -> FC--: Обработка завершена
    FC -> Journal : Записать событие: обработка_успешна

  else
    ' === Ветка 2: Антивирусная проверка ===
    FC -> AV++: Проверить файл
    AV -> FC--: Обработка завершена

  break Файл заражен
    FC -> Storage : Удалить файл
    FC -> Journal : Записать событие: файл_заражен
    FC -> User : Ошибка: попытка загрузить зараженный файл
  end
    FC -> Storage : Пометить как безопасный
end

== Опциональная публикация ссылки ==
opt Пользователь выбрал «создать публичную ссылку»
    FC -> Storage ++: Создать публичную ссылку
    Storage --> FC --: Ссылка
    FC -> FC : Активировать ссылку
end

FC -> Journal : Записать событие: загрузка_успешна
FC -> User : Уведомить: загрузка завершена

@enduml
