//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.cpp
//  @ Date : 19.12.2025
//  @ Author : 
//
//


#include "Admin.h"
#include "User.h"
#include "CloudStorage.h"

void Admin::manage(User user, CloudStorage storage) {

}

