//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DownloadManager.cpp
//  @ Date : 19.12.2025
//  @ Author : 
//
//


#include "DownloadManager.h"
#include "User.h"
#include "CloudFile.h"
#include "CloudStorage.h"
#include "DownloadTask.h"

void DownloadManager::startDownload(User user, CloudFile file, CloudStorage storage) {

}

void DownloadManager::cancelDownload(DownloadTask task) {

}

