//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DownloadTask.cpp
//  @ Date : 19.12.2025
//  @ Author : 
//
//


#include "DownloadTask.h"
#include "CloudFile.h"
#include "User.h"

void DownloadTask::start(CloudFile file, User user) {

}

void DownloadTask::cancel() {

}

List<Byte> DownloadTask::getPartData() {

}

