//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 19.12.2025
//  @ Author : 
//
//


#include "User.h"
#include "CloudFile.h"
#include "DownloadManager.h"
#include "CloudStorage.h"

void User::requestDownload(CloudFile file, DownloadManager manager) {

}

void User::listFiles(CloudStorage storage) {

}

