//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : VideoFile.cpp
//  @ Date : 19.12.2025
//  @ Author : 
//
//


#include "VideoFile.h"

String VideoFile::getResolution() {

}

List<Byte> VideoFile::read() {

}

